// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-O9ktPpOOJ4SQA6AUbpYDlArszJrgBR8',
    appId: '1:306849758566:web:063d5c3ab755826f75dca7',
    messagingSenderId: '306849758566',
    projectId: 'logicfuzzy',
    authDomain: 'logicfuzzy.firebaseapp.com',
    databaseURL: 'https://logicfuzzy-default-rtdb.firebaseio.com',
    storageBucket: 'logicfuzzy.appspot.com',
    measurementId: 'G-KY9SWXMQ7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF5bGe0gUfjuKtdFzlevw6aG2rzD5NSto',
    appId: '1:306849758566:android:df0f87b4dd3fe01875dca7',
    messagingSenderId: '306849758566',
    projectId: 'logicfuzzy',
    databaseURL: 'https://logicfuzzy-default-rtdb.firebaseio.com',
    storageBucket: 'logicfuzzy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7UENcJXbHbUydvyeM0VSV6bRn3fda7Pw',
    appId: '1:306849758566:ios:87d8ce2701347e6575dca7',
    messagingSenderId: '306849758566',
    projectId: 'logicfuzzy',
    databaseURL: 'https://logicfuzzy-default-rtdb.firebaseio.com',
    storageBucket: 'logicfuzzy.appspot.com',
    androidClientId: '306849758566-eq38eenfne5nsarus68ee0gmdm7erqi0.apps.googleusercontent.com',
    iosClientId: '306849758566-hk7ulh55a93h6ddn0kmdvp4erejni15v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFuzzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7UENcJXbHbUydvyeM0VSV6bRn3fda7Pw',
    appId: '1:306849758566:ios:d97333357f343a4575dca7',
    messagingSenderId: '306849758566',
    projectId: 'logicfuzzy',
    databaseURL: 'https://logicfuzzy-default-rtdb.firebaseio.com',
    storageBucket: 'logicfuzzy.appspot.com',
    androidClientId: '306849758566-eq38eenfne5nsarus68ee0gmdm7erqi0.apps.googleusercontent.com',
    iosClientId: '306849758566-1sjdp0b77c4ek11k6423ufirp2mkggf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFuzzy.RunnerTests',
  );
}
